version: '3.1'
services:
  zabbix-pgsql:
    container_name: zabbix-pgsql
    hostname: zabbix-pgsql
    image: postgres:15.1-bullseye
    restart: always
    environment:
      - POSTGRES_PASSWORD=zabbix
    volumes:
      - ./zabbix/zabbix-pgsql:/var/lib/postgresql/data
    networks:
      lab-zabbix:
        ipv4_address: 10.0.0.2
    ports:
      - 5432:5432

  zabbix-server:
    container_name: zabbix-server
    hostname: zabbix-server
    image: zabbix/zabbix-server-pgsql:ol-trunk
    restart: always
    environment:
      - DB_SERVER_HOST=10.0.0.2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zabbix
    volumes:
      - ./zabbix/zabbix-server-module:/var/lib/zabbix/modules
    networks:
      lab-zabbix:
        ipv4_address: 10.0.0.3
    ports:
      - 10051:10051
      - 10050:10050
    depends_on:
      - zabbix-pgsql

  zabbix-frontend:
    container_name: zabbix-frontend
    hostname: zabbix-frontend
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-trunk
    restart: always
    environment:
      - DB_SERVER_HOST=10.0.0.2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zabbix
      - ZBX_SERVER_HOST=10.0.0.3
      - PHP_TZ=America/Belem
    ports:
      - 80:8080
    networks:
      lab-zabbix:
        ipv4_address: 10.0.0.4
    depends_on:
      - zabbix-pgsql
      - zabbix-server

  nginx-web1:
    container_name: nginx-web1
    hostname: nginx-web1
    image: ubuntu/nginx
    restart: always
    volumes:
      - ./nginx/web1:/usr/share/nginx/html
    ports:
      - 9000:80
    networks:
      lab-zabbix:
        ipv4_address: 10.0.0.10
    depends_on:
      - zabbix-agent

  nginx-web2:
    container_name: nginx-web2
    hostname: nginx-web2
    image: ubuntu/nginx
    restart: always
    volumes:
      - ./nginx/web2:/usr/share/nginx/html
    ports:
      - 9001:80
    networks:
      lab-zabbix:
        ipv4_address: 10.0.0.11
    depends_on:
      - zabbix-agent

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:latest
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Senha do administrador do Grafana
    ports:
      - 3000:3000
    networks:
      lab-zabbix:
        ipv4_address: 10.0.0.20
    depends_on:
      - zabbix-server

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent:ubuntu-trunk
    restart: always
    environment:
      - ZBX_HOSTNAME=nginx-web1  # Nome do host do primeiro Nginx (ou nginx-web2)
      - ZBX_SERVER_HOST=10.0.0.3  # Endereço do servidor Zabbix
    networks:
      lab-zabbix:
        ipv4_address: 10.0.0.30
    depends_on:
      - zabbix-server

networks:
  lab-zabbix:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24  # Sub-rede da rede
          gateway: 10.0.0.1  # Gateway da rede
